name: Test and Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and launch the Docker Compose
        run: |
          docker-compose build
          docker-compose up -d

      - name: Wait for DB
        run: sleep 20

      - name: Create Database
        run: docker-compose run --rm web rails db:create

      - name: Run Tests inside Docker Container
        run: docker-compose run --rm web bundle exec rails test
