name: Test and Deploy

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache bundle
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: bundle-v1-${{ hashFiles('Gemfile.lock') }}

      - name: Cache yarn
        uses: actions/cache@v2
        with:
          path: node_modules
          key: yarn-v1-${{ hashFiles('yarn.lock') }}

      - name: Build and launch the Docker Compose
        run: |
          docker-compose build
          docker-compose up -d

      - name: Wait for DB
        run: sleep 20

      - name: Create Database
        run: docker-compose run --rm web rails db:create

      - name: Run Tests inside Docker Container
        run: docker-compose run --rm web bundle exec rails test

  deploy:
    name: Deploy app to EC2
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no -A ec2-user@${{ secrets.TARGET_HOSTNAME }} "\
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ec2-user:latest && \
            docker-compose down && \
            docker-compose up -d"
