name: Test and Deploy

on:
  push:
    branches:
      - main
  pull_request:
jobs:
   test:
     name: Test
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v2

       - uses: ruby/setup-ruby@v1
         with:
           ruby-version: 3.1

       - name: Run bundle install
         run: |
           bundle config --local path vendor/bundle
           bundle config --local without production
           bundle install

       - run: bundle exec rails test
