name: Test and Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --file Dockerfile -t realworld

      - name: Launch the Docker Compose
        run: docker-compose up -d

      - name: Wait for DB
        run: sleep 20

      - name: Create Database
        run: docker-compose run --rm web rails db:create

      - name: Run Tests inside Docker Container
        run: |
          docker run \
            -e RAILS_ENV=test \
            -e DATABASE_HOST=db \
            -e DATABASE_USERNAME=root \
            -e DATABASE_PASSWORD=password \
            -p 3000:3000 \
            realworld bundle exec rails test
